{
  "hash": "ca7d7a9e2f55cd4e2ab482016d595f78",
  "result": {
    "engine": "jupyter",
    "markdown": "## Estrategia de Splitting Temporal {#sec-temporal-splitting}\n\n### \u00bfPor qu\u00e9 Out-of-Time y no Random Split?\n\nEn la pr\u00e1ctica bancaria, un modelo de PD se entrena con datos hist\u00f3ricos y se aplica a solicitantes futuros. La evaluaci\u00f3n relevante es: **\u00bfqu\u00e9 tan bien predice el modelo sobre datos de un per\u00edodo que no vio durante el entrenamiento?** Un split aleatorio mezcla pr\u00e9stamos de todos los per\u00edodos en train y test, permitiendo que el modelo \"vea\" el futuro --- por ejemplo, patrones de 2019 que informan predicciones sobre pr\u00e9stamos de 2018.\n\nEl **split Out-of-Time (OOT)** replica el escenario de producci\u00f3n: el modelo se entrena con el pasado y se eval\u00faa exclusivamente con el futuro.\n\n::: {.callout-warning}\n## Random split infla el AUC\nExperimentos internos muestran que un random split produce AUC ~0.04 puntos m\u00e1s alto que el split OOT equivalente para el mismo modelo CatBoost. Esta inflaci\u00f3n no se traduce en rendimiento real y da una falsa sensaci\u00f3n de seguridad. El split OOT es la \u00fanica evaluaci\u00f3n metodol\u00f3gicamente v\u00e1lida para un modelo de credit scoring que ser\u00e1 desplegado en producci\u00f3n.\n:::\n\n### Dise\u00f1o del Split Temporal\n\nEl split se implementa en `src/data/prepare_dataset.py` con una fecha de corte en **enero 2018**:\n\n::: {#tbl-temporal-splits .cell tbl-cap='Splits temporales Out-of-Time del proyecto' execution_count=1}\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Split</th>\n      <th>Per\u00edodo</th>\n      <th>Pr\u00e9stamos</th>\n      <th>Default Rate</th>\n      <th>Rol</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Train</td>\n      <td>Jun 2007 \u2014 Mar 2017</td>\n      <td>1,346,311</td>\n      <td>18.52%</td>\n      <td>Entrenamiento del modelo PD (CatBoost + LR)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Calibraci\u00f3n</td>\n      <td>Mar 2017 \u2014 Dic 2017</td>\n      <td>237,584</td>\n      <td>22.20%</td>\n      <td>Scores conformales (MAPIE), calibraci\u00f3n de pro...</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Test (OOT)</td>\n      <td>Ene 2018 \u2014 Sep 2020</td>\n      <td>276,869</td>\n      <td>21.98%</td>\n      <td>Evaluaci\u00f3n final, backtesting, portafolio, IFRS9</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Justificaci\u00f3n de las Fechas de Corte {#sec-cutoff-dates}\n\nLa elecci\u00f3n de enero 2018 como fecha de corte no es arbitraria --- responde a tres criterios:\n\n**1. Representatividad del per\u00edodo de test**: El per\u00edodo 2018--2020 incluye condiciones econ\u00f3micas diversas: expansi\u00f3n econ\u00f3mica (2018--2019) y el inicio de la crisis COVID-19 (2020Q1--Q3). Esto eval\u00faa la robustez del modelo bajo cambio de r\u00e9gimen (*concept drift*).\n\n**2. Tama\u00f1o suficiente para calibraci\u00f3n conformal**: El set de calibraci\u00f3n (237,584 pr\u00e9stamos) es grande comparado con el requisito m\u00ednimo para predicci\u00f3n conformal. El error de muestra finita es $\\frac{1}{n+1} \\approx 4.2 \\times 10^{-6}$, haciendo la garant\u00eda de cobertura pr\u00e1cticamente exacta (ver @sec-coverage-guarantee).\n\n**3. Consistencia con la pr\u00e1ctica bancaria**: Los modelos de PD se recalibran t\u00edpicamente cada 12--24 meses. Tener un test set de ~33 meses simula un ciclo de vida realista del modelo antes de su revisi\u00f3n.\n\n### El Rol Dual del Set de Calibraci\u00f3n {#sec-calibration-role}\n\nEl set de calibraci\u00f3n cumple **dos funciones** independientes en el pipeline:\n\n| Funci\u00f3n | M\u00e9todo | Input | Output |\n|---------|--------|-------|--------|\n| **Calibraci\u00f3n de probabilidades** | Venn-Abers / Platt / Isotonic | Scores CatBoost + labels | Calibrador persistido (`.pkl`) |\n| **Conformizaci\u00f3n** | MAPIE SplitConformalRegressor | PDs calibradas + labels | Cuantiles conformales por grupo |\n\n: Funciones del set de calibraci\u00f3n {#tbl-calibration-functions}\n\nEstas dos funciones se ejecutan secuencialmente --- primero se ajusta el calibrador sobre el set de calibraci\u00f3n, y luego se calculan los scores conformales usando las predicciones calibradas sobre el **mismo** set de calibraci\u00f3n.\n\n::: {.callout-note}\n## \u00bfReutilizar el set de calibraci\u00f3n para ambas funciones?\nUsar el mismo set para calibraci\u00f3n de probabilidades y para conformizaci\u00f3n introduce una dependencia que, en teor\u00eda, podr\u00eda afectar la garant\u00eda de cobertura conformal. En la pr\u00e1ctica, con $n = 237{,}584$ observaciones, el efecto es negligible y la cobertura emp\u00edrica (92.57% al nivel 90%) confirma que la garant\u00eda se mantiene holgadamente. La alternativa --- dividir el set de calibraci\u00f3n en dos --- reducir\u00eda el tama\u00f1o de ambos subsets sin beneficio pr\u00e1ctico medible.\n:::\n\n### Extracci\u00f3n Temporal del Set de Calibraci\u00f3n\n\nA diferencia de una extracci\u00f3n aleatoria, el set de calibraci\u00f3n se extrae del **final** del per\u00edodo de entrenamiento (los \u00faltimos meses antes del corte OOT):\n\n```{=html}\n<div class=\"book-band\">\n  <div class=\"book-band__row\">\n    <div class=\"book-band__segment book-band__segment--train\">\n      <strong>Train</strong>\n      <span>Jun 2007 \u2014 Mar 2017</span>\n      <span>Aprende patrones hist\u00f3ricos y estructura base del score.</span>\n    </div>\n    <div class=\"book-band__segment book-band__segment--cal\">\n      <strong>Calibraci\u00f3n</strong>\n      <span>Mar 2017 \u2014 Dic 2017</span>\n      <span>Sirve para calibrar probabilidades y medir el error t\u00edpico que usar\u00e1 conformal.</span>\n    </div>\n    <div class=\"book-band__segment book-band__segment--test\">\n      <strong>Test OOT</strong>\n      <span>Ene 2018 \u2014 Sep 2020</span>\n      <span>Eval\u00faa rendimiento real sobre el futuro, incluyendo cambio de r\u00e9gimen.</span>\n    </div>\n  </div>\n  <p class=\"book-band__note\">La calibraci\u00f3n se toma del tramo final del entrenamiento para parecerse m\u00e1s al mundo que luego ver\u00e1 el test OOT.</p>\n</div>\n```\n\nEsta estrategia temporal tiene dos ventajas:\n\n1. **Distribuci\u00f3n m\u00e1s cercana al test**: Los pr\u00e9stamos de calibraci\u00f3n (2017) son m\u00e1s recientes que los de train (2007--2017), por lo que su distribuci\u00f3n de features est\u00e1 m\u00e1s cercana a la del test (2018--2020). Esto mejora la relevancia de los cuantiles conformales.\n2. **Preserva el orden temporal en train**: El set de train retiene los pr\u00e9stamos m\u00e1s antiguos \u00edntegramente, evitando \"huecos\" temporales que podr\u00edan afectar modelos de supervivencia o series de tiempo.\n\n### Distribuci\u00f3n del Default Rate por Per\u00edodo\n\nUn aspecto notable del dataset es el **incremento de la tasa de default** en los per\u00edodos m\u00e1s recientes:\n\n| Per\u00edodo | Default Rate | Interpretaci\u00f3n |\n|---------|-------------|---------------|\n| 2007--2012 | ~15--18% | Pr\u00e9stamos maduros, criterios originaci\u00f3n variables |\n| 2013--2016 | ~17--20% | Expansi\u00f3n de Lending Club, base m\u00e1s amplia |\n| 2017 (calibraci\u00f3n) | 22.20% | Relajaci\u00f3n de est\u00e1ndares pre-crisis |\n| 2018--2020 (test) | 21.98% | Incluye impacto COVID-19 en 2020 |\n\n: Default rate por per\u00edodo temporal {#tbl-default-rates}\n\nEl incremento de ~18.5% a ~22% entre train y test representa un **concept drift moderado** --- suficiente para estresar el modelo pero no para invalidarlo. La cobertura conformal de 92.57% (superior al target del 90%) confirma que el pipeline es robusto a este nivel de drift.\n\n### Validaci\u00f3n de la Estrategia\n\nPara validar que el split temporal no introduce sesgos sistem\u00e1ticos, verificamos:\n\n1. **No overlap temporal**: Ning\u00fan pr\u00e9stamo del set de test tiene `issue_d` anterior a enero 2018. Esta garant\u00eda se implementa en `prepare_dataset.py` con un filtro estricto por fecha.\n2. **Consistencia de features**: Las distribuciones de features clave (DTI, FICO, loan_amount) entre train y test son similares, con PSI (Population Stability Index) < 0.10 para la mayor\u00eda de variables.\n3. **Reproducibilidad**: La misma semilla aleatoria (`random_state=42`) y fecha de corte (`2018-01-01`) producen splits id\u00e9nticos en cada ejecuci\u00f3n.\n\n::: {.callout-tip}\n## Implicaci\u00f3n para el lector\nTodas las m\u00e9tricas reportadas en este libro --- AUC, Brier, cobertura conformal, ECL, retorno de portafolio --- se calculan **exclusivamente** sobre el set de test OOT (2018--2020). Ninguna m\u00e9trica se reporta sobre datos de entrenamiento o validaci\u00f3n. Esto garantiza que los n\u00fameros reflejan rendimiento genuino en un escenario prospectivo, no sobreajuste al pasado.\n:::\n\n",
    "supporting": [],
    "filters": []
  }
}
