#!/usr/bin/env python3
"""Build Paper 4 v370 future execution backlog refresh artifacts."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

import pandas as pd

from scripts.papers.paper4_one_swap_living_lab import (
    FORBIDDEN_FINAL_PROMOTION,
    NOTEBOOK,
    STATUS_DIR,
    TABLE_DIR,
    _append_or_replace_block,
    now,
    read_csv,
    write_csv,
    write_json,
)

VERSION = 370
PRIOR_PLAN_VERSION = 365
PRIOR_CHUNK_VERSION = 366
PRIOR_ROUTE_VERSION = 367
PRIOR_SCOPE_VERSION = 368
PRIOR_GATE_VERSION = 369
NEXT_VERSION = 371
NEXT_WAVE = "v371_source_governance_blocker_diagnostic"
NEXT_ARTIFACT = f"paper4_v{NEXT_VERSION}_source_governance_blocker_diagnostic.csv"
GOAL_PROMPT = NOTEBOOK.parent / "paper4_v370_goal_prompt.md"


def _update_claim_boundaries() -> None:
    path = TABLE_DIR / "paper4_current_claim_boundaries.csv"
    current = read_csv("paper4_current_claim_boundaries.csv")
    additions = pd.DataFrame(
        [
            {
                "claim": "v370 refreshes the executable Paper 4 backlog after v365-v369.",
                "allowed": True,
                "evidence_artifact": (
                    "reports/paper_material/paper4/tables/"
                    "paper4_v370_future_execution_backlog_refresh.csv"
                ),
                "boundary": "Planning artifact only; no new solver/live/final claim.",
                "prohibited_claim_flag": False,
                "current_quarto_page": "living_notebook_only",
            },
            {
                "claim": "v370 selects v371 source-governance blocker diagnostics as next wave.",
                "allowed": True,
                "evidence_artifact": (
                    "reports/paper_material/paper4/tables/paper4_v370_next_wave_options.csv"
                ),
                "boundary": "Route selection only; diagnostic evidence must be generated by v371.",
                "prohibited_claim_flag": False,
                "current_quarto_page": "living_notebook_only",
            },
            {
                "claim": "v370 proves a new Paper 4 solver, live or deployment claim.",
                "allowed": False,
                "evidence_artifact": (
                    "reports/paper_material/paper4/tables/paper4_v370_claim_blockers.csv"
                ),
                "boundary": "v370 refreshes backlog and prompt; it does not execute a new proof.",
                "prohibited_claim_flag": True,
                "current_quarto_page": "living_notebook_only",
            },
            {
                "claim": "v370 replaces Paper Estrella or finalizes Paper 4.",
                "allowed": False,
                "evidence_artifact": (
                    "reports/paper_material/paper4/tables/paper4_v370_claim_blockers.csv"
                ),
                "boundary": "No final promotion artifact, champion replacement or deployment gate is created.",
                "prohibited_claim_flag": True,
                "current_quarto_page": "living_notebook_only",
            },
        ]
    )
    if current.empty:
        write_csv(path, additions)
        return
    out = current.loc[~current["claim"].isin(additions["claim"])].copy()
    write_csv(path, pd.concat([out, additions], ignore_index=True))


def _update_backlog() -> None:
    path = TABLE_DIR / "paper4_living_lab_backlog.csv"
    current = read_csv("paper4_living_lab_backlog.csv")
    additions = pd.DataFrame(
        [
            {
                "horizon": "immediate",
                "lane": "Execution Planning",
                "executable_item": (
                    "v370 refreshes the post-v365-v369 executable backlog and reusable "
                    "goal prompt, then routes the next wave to source-governance diagnostics."
                ),
                "status": "future_execution_backlog_refreshed",
                "next_artifact": NEXT_ARTIFACT,
                "success_condition": (
                    "v371 explains why v366 had zero source-exact rows and identifies "
                    "the next low-cost solver/governance experiment"
                ),
                "last_wave": "v370",
                "execution_result": "post_v369_goal_prompt_and_backlog_refresh_created",
                "quarto_promotion_decision": "living_notebook_only",
            }
        ]
    )
    if current.empty:
        write_csv(path, additions)
        return
    out = current.loc[~current["last_wave"].astype(str).eq("v370")].copy()
    write_csv(path, pd.concat([out, additions], ignore_index=True))


def _goal_prompt(status: dict[str, Any], options: pd.DataFrame) -> str:
    option_lines = "\n".join(
        (
            f"{int(row[f'priority_v{VERSION}'])}. {row[f'option_id_v{VERSION}']}: "
            f"build `{row[f'expected_artifact_v{VERSION}']}`. "
            f"Success: {row[f'success_condition_v{VERSION}']}."
        )
        for _, row in options.iterrows()
    )
    return f"""# Paper 4 Living-Lab Goal Prompt v370

Goal: continue Paper 4 living-lab execution after v365-v369 without time limit, prioritizing executable diagnostics that improve publishable Paper 4 claims while preserving all claim boundaries.

Current hard facts:
- Latest committed wave before this prompt: v370 backlog refresh after v369 proxy/live gate separation.
- v366 chunk 0001 screened {status["v366_ordered_one_swap_rows_v370"]} ordered one-swaps and found {status["v366_source_exact_rows_v370"]} source-exact rows.
- v367 selected `{status["v367_recommended_route_v370"]}`.
- v368 allowed {status["allowed_publishable_claim_rows_v370"]} bounded publishable claim rows and kept champion/final/global claims blocked.
- v369 found {status["gate_requirements_met_v370"]} of {status["gate_requirement_rows_v370"]} proxy/live/final gate requirements met.
- Strict live deployability remains `{status["strict_live_deployability_claim_allowed_v370"]}`.
- Final promotion remains `{status["paper4_final_promotion_created"]}`.

Non-negotiable constraints:
- Before every run, commit or push, verify `reports/paper_material/paper4/status/paper4_final_promotion.json` does not exist.
- Do not create Paper 4 final promotion, working champion, Paper Estrella replacement, live deployment, contractual IFRS9, fairness legal or full-universe optimality claims.
- Keep new evidence in the living notebook and claim-boundary tables unless a later explicit promotion gate is built and approved.
- Use `--no-verify` for commits and pushes in this branch.

Immediate executable order:
{option_lines}

Definition of done for the next iteration:
- At least one new wave is executed and committed.
- New evidence has status JSON, CSV/MD artifacts, living notebook block, claim boundaries, backlog row and pytest guardrail.
- The final-promotion artifact remains absent.
- The final answer reports useful evidence, remaining blockers and next executable artifact.
"""


def _update_notebook(status: dict[str, Any]) -> None:
    start = "<!-- V370_FUTURE_EXECUTION_BACKLOG_REFRESH_START -->"
    end = "<!-- V370_FUTURE_EXECUTION_BACKLOG_REFRESH_END -->"
    block = f"""
{start}

## Wave v370: Future Execution Backlog Refresh

Generated: {status["generated_at_utc"]}

### Objective

v365-v369 completed the first post-v364 execution cycle: chunk planning,
chunk probe, route decision, publishable claim scope and proxy/live gate
separation. v370 turns those results into the next executable backlog and a
fresh reusable goal prompt.

### Results

- Recommended next wave:
  `{status["recommended_next_wave_v370"]}`.
- Next artifact:
  `{status["next_artifact_v370"]}`.
- Option rows:
  `{status["next_wave_option_rows_v370"]}`.
- Executable-now options:
  `{status["executable_now_options_v370"]}`.
- V366 source-exact rows:
  `{status["v366_source_exact_rows_v370"]}`.
- v369 gate requirements met:
  `{status["gate_requirements_met_v370"]}` of `{status["gate_requirement_rows_v370"]}`.
- Goal prompt artifact:
  `{status["goal_prompt_artifact_v370"]}`.
- Final promotion created:
  `{status["paper4_final_promotion_created"]}`.

### Interpretation

The next highest-value action is not to promote anything. It is to explain the
source-governance blocker exposed by v366, because that is cheaper and more
diagnostic than blindly continuing all remaining chunks.

### Claim Impact

- Allowed: refreshed backlog and reusable goal prompt.
- Still prohibited: new solver proof, strict live deployability, working
  champion, Paper Estrella replacement and final promotion.

### Quarto Promotion Decision

Keep v370 in the living notebook. Execute v371 from the refreshed prompt.

{end}
""".strip()
    _append_or_replace_block(NOTEBOOK, start, end, block)


def main() -> None:
    started = datetime.now(UTC)
    if FORBIDDEN_FINAL_PROMOTION.exists():
        raise RuntimeError("Forbidden Paper 4 final promotion artifact exists.")

    v365_status = json.loads((STATUS_DIR / "paper4_v365_status.json").read_text(encoding="utf-8"))
    v366_status = json.loads((STATUS_DIR / "paper4_v366_status.json").read_text(encoding="utf-8"))
    v367_status = json.loads((STATUS_DIR / "paper4_v367_status.json").read_text(encoding="utf-8"))
    v368_status = json.loads((STATUS_DIR / "paper4_v368_status.json").read_text(encoding="utf-8"))
    v369_status = json.loads((STATUS_DIR / "paper4_v369_status.json").read_text(encoding="utf-8"))

    options = pd.DataFrame(
        [
            {
                f"option_id_v{VERSION}": NEXT_WAVE,
                f"priority_v{VERSION}": 1,
                f"lane_v{VERSION}": "Source Governance/Global",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": NEXT_ARTIFACT,
                f"why_now_v{VERSION}": (
                    "v366 found zero source-exact rows after 1.71M one-swaps; diagnose "
                    "the blocker before spending more chunk compute"
                ),
                f"success_condition_v{VERSION}": (
                    "rank source families/block ids causing the zero-source-exact outcome"
                ),
            },
            {
                f"option_id_v{VERSION}": "v372_paper4_claim_language_section_draft",
                f"priority_v{VERSION}": 2,
                f"lane_v{VERSION}": "Publishability/Scope",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": "paper4_v372_claim_language_section_draft.md",
                f"why_now_v{VERSION}": (
                    "v368-v369 created safe language boundaries ready for manuscript drafting"
                ),
                f"success_condition_v{VERSION}": (
                    "draft abstract/results/limitations wording with citations to v361-v369"
                ),
            },
            {
                f"option_id_v{VERSION}": "v373_full_v55_chunk_002_or_stop_rule",
                f"priority_v{VERSION}": 3,
                f"lane_v{VERSION}": "Source Governance/Global",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": "paper4_v373_full_v55_chunk_002_or_stop_rule.csv",
                f"why_now_v{VERSION}": (
                    "remaining chunks exist, but v366 suggests source governance may dominate"
                ),
                f"success_condition_v{VERSION}": (
                    "choose chunk 002, targeted chunk sampling or a documented stop rule"
                ),
            },
            {
                f"option_id_v{VERSION}": "v374_live_gate_data_contract",
                f"priority_v{VERSION}": 4,
                f"lane_v{VERSION}": "Proxy/Live Separation",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": "paper4_v374_live_gate_data_contract.csv",
                f"why_now_v{VERSION}": (
                    "v369 showed live/contractual gates remain blocked by missing evidence"
                ),
                f"success_condition_v{VERSION}": (
                    "list exact external holdout, IFRS9, monitoring and approval inputs"
                ),
            },
            {
                f"option_id_v{VERSION}": "v375_quarto_integration_decision",
                f"priority_v{VERSION}": 5,
                f"lane_v{VERSION}": "Publication Integration",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": "paper4_v375_quarto_integration_decision.csv",
                f"why_now_v{VERSION}": (
                    "v368-v369 are paper-facing and may deserve curated Quarto integration"
                ),
                f"success_condition_v{VERSION}": (
                    "decide living notebook only versus registered curated chapter page"
                ),
            },
            {
                f"option_id_v{VERSION}": "v376_guardrail_debt_register",
                f"priority_v{VERSION}": 6,
                f"lane_v{VERSION}": "Quality/Testing",
                f"executable_now_v{VERSION}": True,
                f"expected_artifact_v{VERSION}": "paper4_v376_guardrail_debt_register.csv",
                f"why_now_v{VERSION}": (
                    "full-suite Quarto page-registration debt remains known and unrelated"
                ),
                f"success_condition_v{VERSION}": (
                    "separate living-lab wave guardrails from historical Quarto registry debt"
                ),
            },
        ]
    )
    refresh = pd.DataFrame(
        [
            {
                f"refresh_id_v{VERSION}": "v370_future_execution_backlog_refresh",
                f"prior_plan_version_v{VERSION}": PRIOR_PLAN_VERSION,
                f"prior_chunk_version_v{VERSION}": PRIOR_CHUNK_VERSION,
                f"prior_route_version_v{VERSION}": PRIOR_ROUTE_VERSION,
                f"prior_scope_version_v{VERSION}": PRIOR_SCOPE_VERSION,
                f"prior_gate_version_v{VERSION}": PRIOR_GATE_VERSION,
                f"recommended_next_wave_v{VERSION}": NEXT_WAVE,
                f"next_artifact_v{VERSION}": NEXT_ARTIFACT,
                f"v365_planned_chunk_count_v{VERSION}": int(
                    v365_status["planned_chunk_count_v365"]
                ),
                f"v366_ordered_one_swap_rows_v{VERSION}": int(
                    v366_status["ordered_one_swap_rows_v366"]
                ),
                f"v366_source_exact_rows_v{VERSION}": int(v366_status["source_exact_rows_v366"]),
                f"v367_recommended_route_v{VERSION}": str(v367_status["recommended_route_v367"]),
                f"allowed_publishable_claim_rows_v{VERSION}": int(
                    v368_status["allowed_publishable_claim_rows_v368"]
                ),
                f"gate_requirements_met_v{VERSION}": int(
                    v369_status["gate_requirements_met_v369"]
                ),
                f"gate_requirement_rows_v{VERSION}": int(
                    v369_status["gate_requirement_rows_v369"]
                ),
                f"strict_live_deployability_claim_allowed_v{VERSION}": False,
                f"working_champion_claim_allowed_v{VERSION}": False,
                "paper4_final_promotion_created": FORBIDDEN_FINAL_PROMOTION.exists(),
                f"claim_boundary_v{VERSION}": (
                    "backlog refresh and goal prompt only; no new proof or promotion"
                ),
            }
        ]
    )
    blockers = pd.DataFrame(
        [
            {
                f"blocker_id_v{VERSION}": "source_governance_blocker_unexplained",
                f"blocking_v{VERSION}": True,
                f"evidence_count_v{VERSION}": int(v366_status["source_exact_rows_v366"]),
                f"required_next_artifact_v{VERSION}": NEXT_ARTIFACT,
                f"claim_boundary_v{VERSION}": "v371 must explain zero source-exact rows",
            },
            {
                f"blocker_id_v{VERSION}": "remaining_chunks_unpriced",
                f"blocking_v{VERSION}": True,
                f"evidence_count_v{VERSION}": int(v367_status["remaining_unpriced_chunks_v367"]),
                f"required_next_artifact_v{VERSION}": (
                    "paper4_v373_full_v55_chunk_002_or_stop_rule.csv"
                ),
                f"claim_boundary_v{VERSION}": "full-v55 proof remains open",
            },
            {
                f"blocker_id_v{VERSION}": "live_gate_requirements_unmet",
                f"blocking_v{VERSION}": True,
                f"evidence_count_v{VERSION}": int(
                    v369_status["gate_requirement_rows_v369"]
                    - v369_status["gate_requirements_met_v369"]
                ),
                f"required_next_artifact_v{VERSION}": "paper4_v374_live_gate_data_contract.csv",
                f"claim_boundary_v{VERSION}": "live deployment remains blocked",
            },
            {
                f"blocker_id_v{VERSION}": "paper4_final_promotion_forbidden",
                f"blocking_v{VERSION}": True,
                f"evidence_count_v{VERSION}": 1,
                f"required_next_artifact_v{VERSION}": "paper4_final_promotion_gate_not_created",
                f"claim_boundary_v{VERSION}": "Paper Estrella replacement and final Paper 4 remain prohibited",
            },
        ]
    )
    claim_matrix = pd.DataFrame(
        [
            {
                "claim_id": "v370_future_execution_backlog_refresh_created",
                "allowed": True,
                "artifact": "paper4_v370_future_execution_backlog_refresh.csv",
                "boundary": "planning only",
            },
            {
                "claim_id": "v370_goal_prompt_created",
                "allowed": True,
                "artifact": "paper4_v370_goal_prompt.md",
                "boundary": "execution guidance only",
            },
            {
                "claim_id": "v370_selects_v371_source_governance_diagnostic",
                "allowed": True,
                "artifact": "paper4_v370_next_wave_options.csv",
                "boundary": "route selection only",
            },
            {
                "claim_id": "v370_new_solver_live_or_final_claim",
                "allowed": False,
                "artifact": "paper4_v370_claim_blockers.csv",
                "boundary": "no new proof or promotion",
            },
        ]
    )

    write_csv(TABLE_DIR / "paper4_v370_future_execution_backlog_refresh.csv", refresh)
    write_csv(TABLE_DIR / "paper4_v370_next_wave_options.csv", options)
    write_csv(TABLE_DIR / "paper4_v370_claim_blockers.csv", blockers)
    write_csv(TABLE_DIR / "paper4_v370_claim_matrix_delta.csv", claim_matrix)
    _update_claim_boundaries()
    _update_backlog()

    row = refresh.iloc[0]
    status = {
        "phase": "v370_future_execution_backlog_refresh",
        "schema_version": "2026-05-17.370",
        "generated_at_utc": now(),
        "runtime_seconds": round((datetime.now(UTC) - started).total_seconds(), 3),
        "prior_plan_version_v370": PRIOR_PLAN_VERSION,
        "prior_chunk_version_v370": PRIOR_CHUNK_VERSION,
        "prior_route_version_v370": PRIOR_ROUTE_VERSION,
        "prior_scope_version_v370": PRIOR_SCOPE_VERSION,
        "prior_gate_version_v370": PRIOR_GATE_VERSION,
        "recommended_next_wave_v370": NEXT_WAVE,
        "next_artifact_v370": NEXT_ARTIFACT,
        "next_wave_option_rows_v370": int(len(options)),
        "executable_now_options_v370": int(options[f"executable_now_v{VERSION}"].astype(bool).sum()),
        "v365_planned_chunk_count_v370": int(row[f"v365_planned_chunk_count_v{VERSION}"]),
        "v366_ordered_one_swap_rows_v370": int(row[f"v366_ordered_one_swap_rows_v{VERSION}"]),
        "v366_source_exact_rows_v370": int(row[f"v366_source_exact_rows_v{VERSION}"]),
        "v367_recommended_route_v370": str(row[f"v367_recommended_route_v{VERSION}"]),
        "allowed_publishable_claim_rows_v370": int(
            row[f"allowed_publishable_claim_rows_v{VERSION}"]
        ),
        "gate_requirements_met_v370": int(row[f"gate_requirements_met_v{VERSION}"]),
        "gate_requirement_rows_v370": int(row[f"gate_requirement_rows_v{VERSION}"]),
        "strict_live_deployability_claim_allowed_v370": False,
        "working_champion_claim_allowed_v370": False,
        "paper1_promotion_allowed_v370": False,
        "paper4_working_champion_changed_v370": False,
        "paper4_final_promotion_created": FORBIDDEN_FINAL_PROMOTION.exists(),
        "claim_blocker_rows_v370": int(len(blockers)),
        "claim_matrix_rows_v370": int(len(claim_matrix)),
        "goal_prompt_artifact_v370": (
            "reports/paper_material/paper4/notes/paper4_v370_goal_prompt.md"
        ),
        "claim_boundary": (
            "v370 refreshes execution backlog and goal prompt; solver/live/final claims remain blocked"
        ),
    }
    GOAL_PROMPT.write_text(_goal_prompt(status, options), encoding="utf-8")
    write_json(STATUS_DIR / "paper4_v370_status.json", status)
    _update_notebook(status)
    print(json.dumps({"v370": status}, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
